engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - bin/**
    - lib/**
    - routes/**
    - server/**
    - views/**
exclude_paths:
    - "node_modules/"
    - "apidoc/"
    - "client/"
    - "config/"
    - "coverage/"
    - "dist/"
    - "public/"
    - "test/"
    - "gulpfile.js"
    - "karma.conf.js"
    - "nightwatch.conf.js"
